[package]
name = "bake-readme-project"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
bake = { package = "socketry-bake", version = "0.2.1", path = "../../bake-rust" }
bake-agent-context = { version = "0.1.0", path = "../../bake-agent-context-rust" }
bake-cargo = { version = "0.2.0", path = "../../bake-cargo-rust" }
bake-license = { version = "0.1.0", path = "../../bake-license-rust" }
bake-readme = { version = "0.1.0", path = ".." }
bake-releases = { version = "0.2.0", path = "../../bake-releases-rust" }
